### ISSUE TITLE
Figure out how to use knockout.js

### ISSUE THREAD

**Issue by RealTayy** [thaiscmky/letseat#15]
* official tutorials: http://learn.knockoutjs.com
* official documentation: http://knockoutjs.com/documentation/introduction.html

**Comment by thaiscmky** [comment]
@RealTayy @Rohan-Menon @yewbdar once you guys know "enough to be dangerous" (get something started), go ahead and close this issue. Whoever is not caught up, just get help from the others who've started something. This is just a generic understanding, you will continue to learn/figure things out through the app. If you can't get something going by tomorrow, go ahead and work on the same items you were working on, but without KO implementation.

We can talk about a definite drop or questions on Tuesday.
