### ISSUE TITLE
Add input validation for landing page

### ISSUE THREAD

**Issue by Rohan-Menon** [thaiscmky/letseat#27]
* Refer to User Story 1 and MVPs

**Comment by thaiscmky** [comment]
@Rohan-Menon I've updated your ticket to implement knockout, if this isn't changed to "In-Progress" today, I will go ahead and separate into a ticket with dummy validation, then merge your code in when you're done.

**Comment by thaiscmky** [comment]
Merged to master
Test on https://github.com/thaiscmky/letseat/pull/114
