### ISSUE TITLE
Come up with a HIGH LEVEL wireframe design based on the following needs

### ISSUE THREAD

**Issue by thaiscmky** [thaiscmky/letseat#5]
List subject to change depending on issue #6 
- [x] Get a list of activities based on zipcode, what to eat, and when
~~- [ ] A list of zip codes~~
- [x] Select what to eat from a list of eating categories OR free-text search (which?)
- [x] A way to create eating activities based on location, what to eat, and when
- [x] Names of activity creators~~
- [x] RSVP/Enrollment/Join option for activities
- [x] A way to limit number of people per  #activity
- [x] A way to notify creator of new activity enrollments (e.g. Email)
~~- [ ] A way to approve people for your activity~~
- [x] A way to notify people selecting to be in an activity of ~~approved~~ enrollments
- [x] A ~~profile~~ section for users to keep track of their created/selected activities based on a unique identifier (uid: **email**) for the user
- [x] A way to end/close an activity
~~- [ ] A way to cancel participation request on activity~~
- [x] A way for table host and activity members to identify themselves to each other when they meet without giving out personal information

**Also see brainstorming story board sketched in class**
https://files.slack.com/files-pri/T8LH6LL9W-F9R28LFFF/image_uploaded_from_ios.jpg
https://files.slack.com/files-pri/T8LH6LL9W-F9QTD7E1G/image_uploaded_from_ios.jpg

**Comment by thaiscmky** [comment]
Wireframes added by Vinanti on slack:
https://files.slack.com/files-pri/T8LH6LL9W-F9S5N4Z71/image_uploaded_from_ios.png
https://files.slack.com/files-pri/T8LH6LL9W-F9R7QMKA9/image_uploaded_from_ios.png
https://files.slack.com/files-pri/T8LH6LL9W-F9R19GTC3/image_uploaded_from_ios.png
https://files.slack.com/files-pri/T8LH6LL9W-F9S5NEWP9/image_uploaded_from_ios.png
https://files.slack.com/files-pri/T8LH6LL9W-F9QHA8G7K/image_uploaded_from_ios.png

**Comment by thaiscmky** [comment]
Guys, I'm going to remove the whole approval process thing. I don't think that's an absolute need. We can probably get away with just having a seat count per event, and just submit emails to people letting them know they joined an event, created an event, or ended an event. In order for them to retrieve a list of what they joined or created (either functional or non-functional requirement), we can just add "email address" as one of the input fields required before getting a list of activities. Thoughts @Rohan-Menon @vinantinaik @RealTayy @yewbdar ?

**Comment by RealTayy** [comment]
I think the email is a must because we our users to be able to get into the website to see what activities they joined in case they forget...

Also, I think the time/date for each event is a must. Or else when are they going to know when to show up? It also can be used to automatically "finish" events once their time has passed.

@thaiscmky @vinantinaik @Rohan-Menon @yewbdar

**Comment by thaiscmky** [comment]
`Also, I think the time/date for each event is a must`
@RealTayy I agree with that, but that would probably be part of the first item: we can't show a list based on *when* without having some way to store that *when*. I'm adding wording to the item _A way to create eating activities_ to better account for that

**Comment by thaiscmky** [comment]
Please refer to requirements or MVP on either issue #6 or #23 pulling @RealTayy 's resolution and closing issue
