### ISSUE TITLE
re-add suggestionlist  and integrate it into the main.js viewmodel

### ISSUE THREAD

**Issue by Rohan-Menon** [thaiscmky/letseat#78]

**Comment by RealTayy** [comment]
Hey Rohan don't worry about doing this as I'm revamping the landing page styling. I've completed this on my new landing.

**Comment by thaiscmky** [comment]
Part of #87 ; pending merge to staging (assigning to myself as a reminder). Specific item, so reopening so that we can track progress. @RealTayy If there are any other issue numbers that relate to your Styling issue, could you add references to those on #87? Thanks!

**Comment by thaiscmky** [comment]
Tested and merged to master.
