### ISSUE TITLE
Stylize and add animations to landing-display

### ISSUE THREAD

**Issue by RealTayy** [thaiscmky/letseat#86]

**Comment by RealTayy** [comment]
I've completed the new styling for the landing page. refer to branch "style-landing" to check it out. When merging this to staging/master. I've kept the basic functionality of the original landing page so it's easier to merge HTMLs.

**Comment by thaiscmky** [comment]
Reopening issue as it still needs to be merged to staging and tested. Assigning to myself as a reminder.

**Comment by thaiscmky** [comment]
Tested and merged to master.
